In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [5]:
#convert the data into Pytorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

/tmp/ipykernel_1156/2652044554.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float32)
/tmp/ipykernel_1156/2652044554.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y, dtype=torch.long)


In [13]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [6]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [4]:
from torch.utils.data import Dataset, DataLoader

In [7]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [8]:
dataset = CustomDataset(X,y)

In [9]:
len(dataset)

10

In [10]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [14]:
dataloader = DataLoader(dataset,batch_size=2, shuffle = False)

In [15]:
for batch_features, batch_labels in dataloader:
  print(batch_features,batch_labels)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]]) tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]]) tensor([0, 0])
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]]) tensor([0, 1])
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]]) tensor([1, 1])
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]]) tensor([1, 0])


In [16]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [18]:
df.shape

(569, 33)

In [19]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [23]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [25]:
X_train_tensor.shape, X_test_tensor.shape, y_train_tensor.shape, y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

In [24]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [26]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [27]:
train_dataset = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataset = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [28]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out=  self.linear(features)
    out = self.sigmoid(out)
    return out

In [29]:
learning_rate = 0.1
epochs = 25

In [30]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

#define loss function
loss_fn = nn.BCELoss()

In [33]:
#define loop
for epoch in range(epochs):

  for batch_features ,batch_labels in train_dataset:

    y_pred = model(batch_features)

    loss = loss_fn(y_pred, batch_labels.view(-1,1))

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

  print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')



Epoch 1/25, Loss: 0.2289
Epoch 2/25, Loss: 0.1011
Epoch 3/25, Loss: 0.1084
Epoch 4/25, Loss: 0.0562
Epoch 5/25, Loss: 0.0961
Epoch 6/25, Loss: 0.0396
Epoch 7/25, Loss: 0.0479
Epoch 8/25, Loss: 0.0318
Epoch 9/25, Loss: 0.0389
Epoch 10/25, Loss: 0.2529
Epoch 11/25, Loss: 0.0408
Epoch 12/25, Loss: 0.0458
Epoch 13/25, Loss: 0.1485
Epoch 14/25, Loss: 0.0435
Epoch 15/25, Loss: 0.0733
Epoch 16/25, Loss: 0.0434
Epoch 17/25, Loss: 0.0155
Epoch 18/25, Loss: 0.0344
Epoch 19/25, Loss: 0.0152
Epoch 20/25, Loss: 0.0589
Epoch 21/25, Loss: 0.0967
Epoch 22/25, Loss: 0.0168
Epoch 23/25, Loss: 0.0489
Epoch 24/25, Loss: 0.0325
Epoch 25/25, Loss: 0.0295


Evaluation

In [35]:
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_dataset:
    y_pred = model(batch_features)
    y_pred_labels = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1)== batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

  overall_accuracy = np.mean(accuracy_list)
  print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.0078
